import fs from 'node:fs/promises';
import path from 'node:path';
import { config } from '../config';

/**
 * Where image bytes live. The database only ever stores a key and a URL (see the `images` table),
 * so swapping this driver for object storage such as S3 or Cloudflare R2 touches nothing else.
 */
export interface StorageDriver {
  /** Stores the bytes under `key` and returns the URL the browser should load. */
  put(key: string, bytes: Buffer, mime: string): Promise<string>;
  delete(key: string): Promise<void>;
}

/** Files on the server's disk under DATA_DIR/uploads, served by the app at /uploads. */
class LocalDiskStorage implements StorageDriver {
  constructor(private readonly directory: string) {}

  private resolve(key: string): string {
    // Keys are generated by the server, but never trust a path: keep it inside the directory.
    const target = path.resolve(this.directory, key);
    if (path.dirname(target) !== path.resolve(this.directory)) throw new Error('Invalid storage key.');
    return target;
  }

  async put(key: string, bytes: Buffer): Promise<string> {
    await fs.mkdir(this.directory, { recursive: true });
    await fs.writeFile(this.resolve(key), bytes);
    return `/uploads/${key}`;
  }

  async delete(key: string): Promise<void> {
    await fs.rm(this.resolve(key), { force: true });
  }
}

export const storage: StorageDriver = new LocalDiskStorage(config.uploadsDir);
